service: rubanonrails
image: rubanalexandre/rubanonrails

registry:
  username: rubanalexandre
  password:
    - KAMAL_REGISTRY_PASSWORD

ssh:
  user: app

volumes:
  - "/storage:/rails/storage"

servers:
  web:
    hosts:
      - 68.183.156.101
    options:
      network: private
    labels:
      traefik.http.routers.rubanonrails-web.rule: Host(`www.rubanonrails.com`)
      traefik.http.routers.rubanonrails-web-secure.entrypoints: websecure
      traefik.http.routers.rubanonrails-web-secure.rule: Host(`www.rubanonrails.com`)
      traefik.http.routers.rubanonrails-web-secure.tls: true
      traefik.http.routers.rubanonrails-web-secure.tls.certresolver: letsencrypt

traefik:
  options:
    publish:
      - "443:443"
    volume:
      - "/letsencrypt/acme.json:/letsencrypt/acme.json"
    network: private
  args:
    entryPoints.web.address: ":80"
    entryPoints.websecure.address: ":443"
    certificatesResolvers.letsencrypt.acme.email: "alexandre@hey.com"
    certificatesResolvers.letsencrypt.acme.storage: "/letsencrypt/acme.json"
    certificatesResolvers.letsencrypt.acme.httpchallenge: true
    certificatesResolvers.letsencrypt.acme.httpchallenge.entrypoint: web

env:
  clear:
    RAILS_SERVE_STATIC_FILES: true
  secret:
    - RAILS_MASTER_KEY
